import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { cookies } from "next/headers";
import { PlayerProvider } from "@/context/PlayerContext";
import { PlayerController } from "@/components/PlayerController";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ безопасно достаем куку
  const cookieStore = await cookies();
  const accessCookie = cookieStore.get("access");
  const token: string | null = accessCookie ? accessCookie.value : null;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
  <ThemeProvider
    attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange
  >
    <Navbar initialAuth={!!token} />

<PlayerProvider>
  <main className="flex-grow pt-16">{children}</main>
  <PlayerController />
</PlayerProvider>


    <Footer />
  </ThemeProvider>
</body>

    </html>
  );
}
